name: India
favicon: null
layout_spectrum: 0.7681
typography_spectrum: 0.42775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#639de7'
    - '#aac6eb'
    - '#546921'
    - '#141105'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
